spring.application.name=Fixify
server.port=8080

# ===============================
# MongoDB
# ===============================
spring.data.mongodb.uri=mongodb+srv://singhravipratap005_db_user:p3xEVTVp8EiMnuS0@fixify.bpqm5h2.mongodb.net/fixifydb?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true

# ===============================
# CORS (React Frontend)
# ===============================
spring.web.cors.allowed-origins=http://localhost:5173,http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

# ===============================
# Multipart File Upload
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# File Upload Directory
# ===============================
file.upload-dir=uploads

# ===============================
# Admin Secret (Backend Only)
# ===============================
fixify.admin.secret=232333

